const items=[
    // {
    //     id:,
    //     ctgry:'',
    //     img:'',
    //     ttl:'',
    //     price:,
    //     desc:'   ',
    // },
    {
        id:1,
        ctgry:'Cldrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLWxQbzB50wOcuJuM67JWBg5KCSx3o0PYaqBzgcm8Oo91BRCnt1ogywxakQkuwr1H9QqY&usqp=CAU',
        ttl:'Cappuccino',
        price:50,
        desc:'cold fresh Cappuccino',
    },
    {
        id:2,
        ctgry:'Cldrnk',
        ttl:'Chocalate coffee',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfoPptnJBeIUYVXVuO37OeiYO-5xvbiMsxWg&usqp=CAU',
        price:60,
        desc:'child Chocalate coffee',
    },
    {
        id:3,
        ctgry:'Cldrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe-3JNHo5ed_d01bR6KRm1xDE4_i4AQfWEXA&usqp=CAU',
        ttl:'Banana Shake',
        price:80,
        desc:'fresh cold Banana Shake',
    },
    {
        id:4,
        ctgry:'Cldrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE5eRQxlvuC77JmHEKrr5Xe3wdBqJf4p6YDw&usqp=CAU',
        ttl:'Strawberry Shake',
        price:80,
        desc:'Strawberry Shake',
    },
    {
        id:5,
        ctgry:'Htdrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2KsJJOdC8bNyTxVAeYVIuC57y_8GsFcA71Q&usqp=CAU',
        ttl:'Milk tea',
        price:20,
        desc:'Hot milk tea',
    },
    {
        id:6,
        ctgry:'Htdrnk',
        img:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR74So0P40pTzRHXYiE7QKFbQaMITWWDQyD0pw2vokg21nDcmTd',
        ttl:'Black tea',
        price:40,
        desc:'Black tea',
    },
    {
        id:7,
        ctgry:'Htdrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIcKVTkyaz4_3JKw5grykApqB4U98u6TLayZqLoyV33cM_uLJiaFpjX4czPevCOjlk8-c&usqp=CAU',
        ttl:'Green tean',
        price:40,
        desc:'',
    },
    {
        id:8,
        ctgry:'Htdrnk',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1zCg4EpjcmIMd9Z5Sl0rTh1iKluILh_d7bQ&usqp=CAU',
        ttl:'Green tea',
        price:40,
        desc:'',
    },
    {
        id:9,
        ctgry:'BnP',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-icVQXhApuVGGb0l1nG_B2BNd8MtZtBtLiw&usqp=CAU',
        ttl:'Donut',
        price:120,
        desc:' Delicious donut cake',
    },
    {
        id:10,
        ctgry:'BnP',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFjFlHWSx4jHs6fy71h_0Y-aXh5H9ooCaGlg&usqp=CAU',
        ttl:'Red velvet pastry',
        price: 80,
        desc:'Taste extra moist and delicious',
    },
    {
        id:11,
        ctgry:'BnP',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPcaqFBJ5y9dP31KlXDPTRpE-9T5QT4UIA3mnHGiIypEtTHi-7Sl63p_6LDKeSF1Ti4zo&usqp=CAU',
        ttl:'Pastries',
        price:80,
        desc:'Choclate, vanilla & strawberry pastries',
    },
    {
        id:12,
        ctgry:'BnP',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRnH_LE3kIuV-LEUXNwdjVv2ACDm8Cv3vUsA&usqp=CAU',
        ttl:'Strawberry puff pastry',
        price:160,
        desc:'',
    },
    {
        id:13,
        ctgry:'Dsrts',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR8mkVicoiANClEqKc1x7cei5pPBeuc4DZmg&usqp=CAU',
        ttl:'Ice-cream',
        price:140,
        desc:'15 flavour ice-creams',
    },
    {
        id:14,
        ctgry:'Dsrts',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEhTvH4DC-h-SLNTa55rHsD5MyGGKkTOsgJw&usqp=CAU',
        ttl:'Fruit salad',
        price:200,
        desc:'This salad is a cocktail of delicious fresh fruits ',
    },
    {
        id:15,
        ctgry:'Dsrts',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKWEoNuCUo378d0gsh6wxirnwfj9-c6YeB2g&usqp=CAU',
        ttl:'Chocalate brownie',
        price:'210',
        desc:'Delicious brownie with butter, flour, cocoa, and espresso',
    },
    {
        id:16,
        ctgry:'Dsrts',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfO3BIXrTmLLTMBACkPMcMhIpK7mgRzOBPOA&usqp=CAU',
        ttl:'Cake',
        price:420,
        desc:'The classic opera cake takes some making, but it is so worth the effort',
    },
    {
        id:17,
        ctgry:'food',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3Aqy7kjjQbxmABSduzIg3uyh_TOOS0_GPGA&usqp=CAU',
        ttl:'Veggie pizza',
        price:300,
        desc:'This Veggie Pizza  one of the best pizzas you have ever had!',
    },
    {
        id:18,
        ctgry:'food',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHr4FiIslJFTrLxaoRgE1djF3rTfgBDS-kOw&usqp=CAU',
        ttl:'Cheese pizza',
        price:360,
        desc:'The crust for this pizza is made mainly out of cheese. A delicious, low-carb',
    },
    {
        id:19,
        ctgry:'food',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBKKB9oMfqOovzgqR0B7ws7aOiJtvhpHOqDw&usqp=CAU',
        ttl:'Veg burger',
        price:'60',
        desc:'',
    },
    {
        id:20,
        ctgry:'food',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQD7fE1Ae7XzsYRuIoT2nqaNVHkpCSzzd9iA&usqp=CAU',
        ttl:'Noodles',
        price:80,
        desc:'Spicy kung pao noodles ',
    },
    {
        id:21,
        ctgry:'food',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG4B31ASBOOaUOhecb8yRzdBdAnq2K05ba2g&usqp=CAU',
        ttl:'Sandwichs',
        price:80,
        desc:'Vegetable sandwich',
    },

]
 export default items;